### ISSUE TITLE
Remove Offensive Words from Word List

### ISSUE THREAD

**Issue by KeenRivals** [bkeroack/wordentropy2#3]
This is a great tool but it is difficult to use in a corporate environment due to many offensive words in the word list. I don't know if your upstream word list denotes offensiveness of words, but I'm aware that the dictionaries used by Android available via AOSP have flags for whether or not they are offensive.

**Comment by bkeroack** [comment]
Thank you for the suggestion. I've added an offensive word filter (along with a few other new options). It is a very rudimentary offensive word list since I couldn't find an appropriately-licensed English offensive word list. Feel free to add more to `data/offensive.txt` and open a pull request.

This is now live on wordentropy.org.
